"""Curated German wordlist for readable student passwords.

Selection rules (deliberate — do not add words casually):
- kid-friendly, neutral nouns (animals, nature, everyday objects);
- 4–7 letters so a two-word password clears AD's 12-char minimum;
- lowercase ASCII only — no umlauts/ß, so the password is unambiguous to type
  on any keyboard and never depends on encoding;
- no visually confusable pairs and nothing embarrassing to hand to a child.

The list is intentionally small enough to stay curated but large enough that a
two-word + digits password is not guessable in practice; every provisioned
account is created with force-change-on-first-login anyway.
"""

from __future__ import annotations

WORDS_DE: tuple[str, ...] = (
    "adler",
    "ampel",
    "anker",
    "apfel",
    "banane",
    "berg",
    "biene",
    "birne",
    "blatt",
    "blume",
    "boot",
    "brot",
    "buch",
    "burg",
    "dach",
    "delfin",
    "drache",
    "ente",
    "erde",
    "esel",
    "feder",
    "fisch",
    "flasche",
    "fluss",
    "frosch",
    "fuchs",
    "gabel",
    "garten",
    "gitarre",
    "hafen",
    "hammer",
    "hase",
    "haus",
    "helm",
    "hemd",
    "honig",
    "hund",
    "insel",
    "kabel",
    "kamel",
    "kante",
    "karte",
    "katze",
    "kerze",
    "kiste",
    "klee",
    "koala",
    "krone",
    "kuchen",
    "lampe",
    "leiter",
    "loewe",
    "mango",
    "maus",
    "meer",
    "melone",
    "mond",
    "motor",
    "nadel",
    "nebel",
    "nest",
    "note",
    "panda",
    "pilz",
    "pinsel",
    "planet",
    "quelle",
    "rabe",
    "rakete",
    "regen",
    "reifen",
    "ring",
    "robbe",
    "rose",
    "saft",
    "schnee",
    "segel",
    "sofa",
    "sonne",
    "spinne",
    "stern",
    "stift",
    "strand",
    "tanne",
    "taube",
    "tiger",
    "tomate",
    "traube",
    "tunnel",
    "vogel",
    "wald",
    "welle",
    "wiese",
    "wolke",
    "wurzel",
    "zebra",
    "zug",
)

__all__ = ["WORDS_DE"]
