#!/bin/sh
set -e
case "$1" in
remove | deconfigure)
    if [ -d /run/systemd/system ]; then
        systemctl stop magister-connector.service || true
        systemctl disable magister-connector.service || true
    fi
    ;;
upgrade | failed-upgrade) ;;
esac
exit 0
